In [4]:
import pandas as pd
import numpy as np

a=pd.read_csv('bitcoin_price_1week_Test - Test.csv')
print(a.head())

           Date     Open     High      Low    Close         Volume  \
0  Aug 07, 2017  3212.78  3397.68  3180.89  3378.94  1,482,280,000
1  Aug 06, 2017  3257.61  3293.29  3155.60  3213.94  1,105,030,000
2  Aug 05, 2017  2897.63  3290.01  2874.83  3252.91  1,945,700,000
3  Aug 04, 2017  2806.93  2899.33  2743.72  2895.89  1,002,120,000
4  Aug 03, 2017  2709.56  2813.31  2685.14  2804.73    804,797,000

       Market Cap
0  52,987,300,000
1  53,720,900,000
2  47,778,200,000
3  46,276,200,000
4  44,666,400,000

In [7]:
print("type:",type(a))
print("columns:",list(a.columns))
print("index:",a.index.tolist())

type: <class 'pandas.DataFrame'>
columns: ['Date', 'Open', 'High', 'Low', 'Close', 'Volume', 'Market Cap']
index: [0, 1, 2, 3, 4, 5, 6]

In [11]:
b=pd.read_excel('Online_Retail.xlsx')
print(b.head())

  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

          InvoiceDate  UnitPrice  CustomerID         Country
0 2010-12-01 08:26:00       2.55     17850.0  United Kingdom
1 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
2 2010-12-01 08:26:00       2.75     17850.0  United Kingdom
3 2010-12-01 08:26:00       3.39     17850.0  United Kingdom
4 2010-12-01 08:26:00       3.39     17850.0  United Kingdom

In [16]:
print("first three rows:")
display(a.head(3))

print("\nlast three rows:")
display(a.tail(3))

print("\nInfo:")
a.info()

print("\nDescribe:")
display(a.describe())

print("\nShape of the DataFrame:", a.shape)

first three rows:

,Date,Open,High,Low,Close,Volume,Market Cap
0,"Aug 07, 2017",3212.78,3397.68,3180.89,3378.94,"1,482,280,000","52,987,300,000"
1,"Aug 06, 2017",3257.61,3293.29,3155.60,3213.94,"1,105,030,000","53,720,900,000"
2,"Aug 05, 2017",2897.63,3290.01,2874.83,3252.91,"1,945,700,000","47,778,200,000"

last three rows:

,Date,Open,High,Low,Close,Volume,Market Cap
4,"Aug 03, 2017",2709.56,2813.31,2685.14,2804.73,"804,797,000","44,666,400,000"
5,"Aug 02, 2017",2727.13,2762.53,2668.59,2710.67,"1,094,950,000","44,950,800,000"
6,"Aug 01, 2017",2871.30,2921.35,2685.61,2718.26,"1,324,670,000","47,321,800,000"

Info:
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        7 non-null      str
 1   Open        7 non-null      float64
 2   High        7 non-null      float64
 3   Low         7 non-null      float64
 4   Close       7 non-null      float64
 5   Volume      7 non-null      str
 6   Market Cap  7 non-null      str
dtypes: float64(4), str(3)
memory usage: 524.0 bytes

Describe:

              Open         High          Low        Close
count     7.000000     7.000000     7.000000     7.000000
mean   2926.134286  3053.928571  2856.340000  2996.477143
std     222.327835   263.148120   224.210701   278.478301
min    2709.560000  2762.530000  2668.590000  2710.670000
25%    2767.030000  2856.320000  2685.375000  2761.495000
50%    2871.300000  2921.350000  2743.720000  2895.890000
75%    3055.205000  3291.650000  3015.215000  3233.425000
max    3257.610000  3397.680000  3180.890000  3378.940000

Shape of the DataFrame: (7, 7)

In [17]:
print("First 3 rows:")
display(b.head(3))

print("\nLast 3 rows:")
display(b.tail(3))

print("\nInfo:")
b.info()

print("\nDescribe:")
display(b.describe())

print("\nShape (rows, columns):", b.shape)

First 3 rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom

Last 3 rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

Info:
<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

Describe:

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

Shape (rows, columns): (541909, 8)

In [26]:
print("loc example (rows 0-2 ,specific columns): ")
display(b.loc[0:2,["InvoiceNo","StockCode","Description"]])

print("\niloc example (first 3 rows,first 3 columns): ")
display(b.iloc[0:3, 0:3])

loc example (rows 0-2 ,specific columns):

  InvoiceNo StockCode                         Description
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER
1    536365     71053                 WHITE METAL LANTERN
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER

iloc example (first 3 rows,first 3 columns):

  InvoiceNo StockCode                         Description
0    536365    85123A  WHITE HANGING HEART T-LIGHT HOLDER
1    536365     71053                 WHITE METAL LANTERN
2    536365    84406B      CREAM CUPID HEARTS COAT HANGER

In [23]:
print(a.head())

           Date     Open     High      Low    Close         Volume  \
0  Aug 07, 2017  3212.78  3397.68  3180.89  3378.94  1,482,280,000
1  Aug 06, 2017  3257.61  3293.29  3155.60  3213.94  1,105,030,000
2  Aug 05, 2017  2897.63  3290.01  2874.83  3252.91  1,945,700,000
3  Aug 04, 2017  2806.93  2899.33  2743.72  2895.89  1,002,120,000
4  Aug 03, 2017  2709.56  2813.31  2685.14  2804.73    804,797,000

       Market Cap
0  52,987,300,000
1  53,720,900,000
2  47,778,200,000
3  46,276,200,000
4  44,666,400,000

In [ ]:

print("loc example (rows 0-2, specific columns):")
display(a.loc[0:2, ["Date", "Open", "High"]])

# iloc: position-based selection
print("\niloc example (first 3 rows, first 3 columns):")
display(a.iloc[0:3, 0:3])

loc example (rows 0-2, specific columns):

           Date     Open     High
0  Aug 07, 2017  3212.78  3397.68
1  Aug 06, 2017  3257.61  3293.29
2  Aug 05, 2017  2897.63  3290.01

iloc example (first 3 rows, first 3 columns):

           Date     Open     High
0  Aug 07, 2017  3212.78  3397.68
1  Aug 06, 2017  3257.61  3293.29
2  Aug 05, 2017  2897.63  3290.01